### ISSUE TITLE
code samples in the guide from github repo?

### ISSUE THREAD

**Issue by evilru** [1DSAG/UI5-Best-Practice#129]
I just stumbled upon a ruby gem which can add code from github to jekyll pages:
<https://github.com/bwillis/jekyll-github-sample>
you can see it in action here: 
<https://bwillis.github.io/2014/05/28/include-github-repo-code-in-jekyll/>

it does not fit in the current setup because of dependencie issues:
```bash
$ bundle add jekyll_github_sample
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies.........
Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (= 3.2.22.5)

  In Gemfile:
    jemoji was resolved to 0.12.0, which depends on
      html-pipeline (~> 2.2) was resolved to 2.14.0, which depends on
        activesupport (>= 2)

    jekyll_github_sample was resolved to 0.3.1, which depends on
      activesupport (~> 4.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```
it might be worth to check if it could be updated to fit in our setup.
bundler is able to [install gems directly form a git repository](https://bundler.io/guides/git.html).

also worth mentioning is the possibility to use gists: <https://github.com/jekyll/jekyll-gist>

How does this sound to you?

**Comment by marianfoo** [comment]
thanks for doing the research.
Unfortunately, in the GitHub Pages environment, there are (understandably) restrections as to which gems can be used. See this list https://pages.github.com/versions/
Unfortunately `jekyll-github-sample` is not included there.

However, `jekyll-gist` is present in the list, so you could use it. 
I think advantage will be there then if you have a larger file and want to show short snippets from it again and again?
These would have to be stored actually under the DSAG.
I am not sure if this is a big advantage instead of a code block in markdown and the link to the sample app.
What do you think?

**Comment by evilru** [comment]
I was not aware of the fact that just a bunch of gems can be used in actions. :(
no, using gists does not really bring any value.

I thought it would be great to show code samples from the sample apps instead of duplicating it.

as this gem can't be used - I close the issue.

**Comment by marianfoo** [comment]
There is one more option, but then you would have to effectively do the build of Jekyll yourself and then commit the finished page to GitHub Pages.
Currently, the build is done entirely by GitHub, so the gems there are understandably restrictive.
The advantage is that we can use all the gems and upgrade the gems (e.g. from Jekyll 3 to version 4).
Can you try the Gem somehow if it really helps us?

**Comment by evilru** [comment]
From my perspective it would, yes - but at the cost of doing the build and deploy not with github actions.
Let's discuss it in the next call.
